server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/streaming/ {
        proxy_pass http://mediaserver-api:5001/api/streaming/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }

    location /api/ {
        proxy_pass http://mediaserver-api:5001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
